name: Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    name: Build and Create Tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.14.1

      - name: Get variables
        id: get_vars
        run: |
          echo "SHORT_SHA={$(git rev-parse --short HEAD)}" >> $GITHUB_OUTPUT
          echo "DATE={$(date +'%D')}" >> $GITHUB_OUTPUT

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'
          cache-dependency-path: 'web/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm i
        working-directory: web

      - name: Run build
        run: pnpm build
        working-directory: web
        env:
          CI: false

      - name: Bump manifest version
        run: node .github/actions/bump-manifest-version.js
        env:
          TGT_RELEASE_VERSION: ${{ github.ref_name }}

      - name: Push manifest change
        uses: EndBug/add-and-commit@v8
        with:
          add: fxmanifest.lua
          push: true
          author_name: Manifest Bumper
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: bump manifest version to ${{ github.ref_name }}'

      - name: Update tag ref
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{ github.ref_name }}

      - name: Bundle files
        run: |
          mkdir -p ./temp/dolu_hud
          mkdir -p ./temp/dolu_hud/web
          cp ./{README.md,config.json,fxmanifest.lua} ./temp/dolu_hud
          cp -r ./{client,server,shared} ./temp/dolu_hud
          cp -r ./web/build ./temp/dolu_hud/web/build
          cd ./temp && zip -r ../dolu_hud.zip ./dolu_hud
      - name: Create Release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        id: auto_release
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: '${{ env.RELEASE_VERSION }}'
          prerelease: true
          files: dolu_hud.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
